SELECT * FROM EMPLOYEES;
SELECT * FROM DEPARTMENTS;
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID = 50;

UPDATE EMPLOYEES SET SALARY = SALARY + 0.3 * SALARY WHERE DEPARTMENT_ID = 50;
UPDATE EMPLOYEES SET MANAGER_ID = NULL WHERE MANAGER_ID = 101;
DELETE FROM EMPLOYEES WHERE EMPLOYEE_ID = 101;

SELECT * FROM EMPLOYEES WHERE JOB_ID = 'IT_PROG' ORDER BY FIRST_NAME;
select count(employee_id) from employees emp where emp.JOB_ID = 'IT_PROG';

SELECT FIRST_NAME, DEPARTMENT_NAME FROM EMPLOYEES
INNER JOIN DEPARTMENTS
ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID 
WHERE EMPLOYEES.DEPARTMENT_ID = 50;

SELECT FIRST_NAME, LOCATION_ID
FROM EMPLOYEES
INNER JOIN DEPARTMENTS
ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID 
WHERE DEPARTMENTS.LOCATION_ID = 1700;

CREATE VIEW MY_VIEW AS
SELECT EMPLOYEE_ID, FIRST_NAME, DEPARTMENT_NAME FROM EMPLOYEES
INNER JOIN DEPARTMENTS
ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID; 

SELECT sysdate from dual;
select to_char(sysdate, 'dd-MM-yyyy') from dual;
select to_date ('25-11-2014', 'dd-MM-yyyy') from dual;

SELECT UPPER(FIRST_NAME), LOWER(EMAIL) FROM EMPLOYEES;
COMMIT
